[package]
name = "farol-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "farol"
path = "src/main.rs"

[dependencies]
farol-protocol = { path = "../farol-protocol" }
iced = { version = "0.14", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1"

[dev-dependencies]
iced_test = "0.14"
insta = "1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
